version: '3.7'


services:

  test_db:
    image: postgres:12.1-alpine
    volumes:
      - postgres_test_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=mychef
      - POSTGRES_PASSWORD=mychef
      - POSTGRES_DB=mychef_db 

  test_api:
    image: lvconnolly/mychef_api:dev
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    environment:
      - MODEL=ingredients_v1
      - POSTGRES_USER=mychef
      - POSTGRES_PASSWORD=mychef
      - POSTGRES_HOST=test_db
      - POSTGRES_DB=mychef_db
    command: uvicorn app.main:app --reload --host 0.0.0.0
    depends_on:
      - test_db


volumes:
    postgres_test_data:
